### ISSUE TITLE
[INPUT] Keys don't press themselves sometimes.

### ISSUE THREAD

**Issue by infernoangel301** [polybiusproxy/PolyEngine#1]
Input needs a fix.

**Comment by polybiusproxy** [comment]
Thanks for your issue! I'm investigating the problem, and it should be fixed as soon as possible.
Update of the issue will be published here, so I won't close.

**Comment by polybiusproxy** [comment]
Now inputs should be better now.
However, there can be problems.

**Comment by polybiusproxy** [comment]
Input is finally fixed! (tell everyone on vs dark group lol)
