### ISSUE TITLE
do you want a mac version?

### ISSUE THREAD

**Issue by McJonnycat** [polybiusproxy/PolyEngine#17]
do you want a mac version of the new polyengine?

**Comment by polybiusproxy** [comment]
that would be cool but im busy with high school

**Comment by Jonnycatmeow** [comment]
> that would be cool but im busy with high school

awww man homework caught up to you

**Comment by the-funky-lad** [comment]
yes

**Comment by McJonnycat** [comment]
well i will make it

**Comment by the-funky-lad** [comment]
you know i could just make it myself, right?
