### ISSUE TITLE
systools doesn't rebuild when you do it

### ISSUE THREAD

**Issue by BushsHaxs** [polybiusproxy/PolyEngine#19]
when i type 
lime rebuild systools
it gives me this error
/Users/runner/hostedtoolcache/haxe/4.1.5/x64/lib/polymod/git/polymod/fs/PolymodFileSystem.hx:18: characters 18-20 : Expected )
(this is for mac)

**Comment by BushsHaxs** [comment]
also i want to make a mac port i just need your permission

**Comment by polybiusproxy** [comment]
go ahead!
