### ISSUE TITLE
TitleState errors

### ISSUE THREAD

**Issue by Epic-Riff** [polybiusproxy/PolyEngine#3]
So I tried building the game and even though I haven't changed anything these errors show up:

source/TitleState.hx:78: lines 78-91 : { modRoot : String, ignoredFiles : Array<String>, frameworkParams : { assetLibraryPaths : haxe.ds.Map<String, String> }, framework : polymod.Framew... has extra field frameworkParams
source/TitleState.hx:78: lines 78-91 : For function argument 'params'
source/TitleState.hx:95: characters 19-30 : You can't iterate on a Dynamic value, please specify Iterator or Iterable

**Comment by polybiusproxy** [comment]
Hi there!
You can't build because PolyEngine uses a modificated version of Polynod.

You can fix it by using these commands:

"haxelib remove polymod"
"haxelib git polynod https://github.com/larsiusprime/polymod funkinfixes"

If that fixed the issue, please close!
