### ISSUE TITLE
Error: Source path "C:/HaxeToolkit/haxe/lib/systools/1,1,0/ndll/Windows64/systools.ndll" does not exist

### ISSUE THREAD

**Issue by BlazeTBV** [polybiusproxy/PolyEngine#37]
he;p

**Comment by GamerPablito** [comment]
@BlazeTBV You have to open the Command Prompt and run these lines:
```
haxelib git systools https://github.com/haya3218/systools
haxelib run lime rebuild systools [windows, mac, linux]
```

Hope it can come in handy with your problem :)

**Comment by FrozenOfficialGITHUB** [comment]
haxelib git systools https://github.com/polybiusproxy/systools.git
haxelib run lime rebuild systools windows
