### ISSUE TITLE
Error with the systools plugin during compilation

### ISSUE THREAD

**Issue by RGameRG** [polybiusproxy/PolyEngine#6]
When compiling, it returns an error about the absence of the windows64 folder in the folder with the systools plugin.
Here's what it outputs in the PowerShell:Source path "C:/HaxeToolkit/haxe/lib/systools/1,1,0/ndll/Windows64/systools.ndll" does not exist.
What do I need to download or do to fix this?

**Comment by RGameRG** [comment]
I'm closing this topic because I found something that fixes this error.(in my case, this helped: I dragged the file from the archive with the 2.1.4 PolyEngine build to the created folder in the place indicated by the error(Windows64))

**Comment by polybiusproxy** [comment]
thats a silly fix
you just could do "lime rebuild windows systools"

**Comment by RGameRG** [comment]
Thank you for tips
